server: 
 port: 8040

spring:
 application:
  name: api-gateway
  
 config:
  import: configserver:http://localhost:8050

 cloud:
  inetutils:
   preferred-networks: 127.0.0.1
   
  gateway:
   routes:
    - id: USER-SERVICE
      uri: lb://USER-SERVICE/
      predicates:
       - Path=/**
       
    - id: HOTEL-SERVICE
      uri: lb://HOTEL-SERVICE/
      predicates:
       - Path=/hotel-app/api/**

    - id: RATING-SERVICE
      uri: lb://RATING-SERVICE/
      predicates:
       - Path=/rating-app/api/**    