spring:
 application:
  name: hotel-service
 cloud:
  inetutils:
   preferred-networks: 127.0.0.1
  
 datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/hotel
  username: root
  password: 654321

# jpa:
#  hibernate:
#   ddl-auto: create


server: 
 port: 8070
 servlet: 
  context-path: /hotel-app/api/
    
eureka:
  client:
   register-with-eureka: true
   fetch-registry: true
   service-url:
    defaultZone: http://localhost:8761/eureka
