spring:
 application:
  name: hotel-service
 cloud:
  inetutils:
   preferred-networks: 127.0.0.1
 config:
  import: configserver:http://localhost:8050
    
 datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/hotel
  username: root
  password: root

# jpa:
#  hibernate:
#   ddl-auto: create


server: 
 port: 8070
 servlet: 
  context-path: /hotel-app/api/
    