spring:
 application:
  name: discovery-hotel-service
 cloud:
  inetutils:
   preferred-networks: 127.0.0.1
  
server:
 port: 8761

eureka:
 instance:
  hostname: localhost
 client: 
  register-with-eureka: false
  fetch-registry: false